name: CMake

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install ninja-build libglfw3-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/dist

    - name: Build
      run: cmake --build ${{github.workspace}}/build --target install

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: marble-linux
        path: ${{github.workspace}}/dist/

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/dist

    - name: Build
      run: cmake --build ${{github.workspace}}/build --target install --config Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: marble-windows
        path: ${{github.workspace}}/dist/
